language: go
go:
- '1.10'
env:
  matrix:
    secure: kH8tGqLkyJZlSm7blnl55oXUTWpHv8syrhr9PuoInYNcaWvgRJkqQvPr3/LUM0DH2+ydKeihzJxLp/RzGviMG4feGN7WguMjitqlcMsMuVtWDEV41YLDUKmxhPRLkQm5T8gBynWVP+e+NaRnPzZW6iWLdAPE2yaniaL9VBbwIJ0NJGSC0Q4u2JgD+4mpUAuCGX6VEFBxBZC28j0DBhxbwHTS4/vVlAXA32x6Bu4+ZC0cB5IZTushjsRyg/Zv12E7+lfclGpoPh3Xvzpx8TcMhDV3+diZXf+DmMsgkVxnR8B0mlh3D06JFJYKj8tgILfcyls+IPSW3vqBbZeQv4Sii0tCxdZKHz09R9uIOO2fl3TM/Z/FLiRLDrelXRn4W90WuWkoBQeIJ9j1q/M4vpTWsluPLMk3MWwhNP40Wi71KYJuzER8xXR2URHZO798lSOcm5Vhbrr+L7qEaZJ4BPocKnieG/kDR+kcXbUM1f5Rb2efzIk/luF7Hflb5Ul3sf8ZaLFKSxs7EO0eljLAfQTGQaGeHjMeEQRRrGdPdew8PUn3B6nZL81B6q3tP78G3u/03vzpayKPe4+cQDRa2g7gj1HaV4m1l2Aw3tN7l/fL8nuXpc/ztVqf0TdqIXSL5Y5ezg5mi7aXt1kTLLftpmUjKlRPbIKHRSFUFtZ+0EUerY0=
